name: Merge PHP images to manifest

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner name i.e. default runner "ubuntu-24.04"
        type: string
        required: true
      image-name:
        description: Image name
        type: string
        required: true

jobs:
  merge:
    name: Merge Images
    runs-on: ${{ inputs.runs-on }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Image name
        id: image_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ inputs.image-name }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create Manifest (runtime)
        uses: atlasbytes/github-actions/create-manifest-for-target@0.4.0
        with:
          image-name: ${{ steps.image_name.outputs.lowercase }}
          target: runtime
      - name: Create Manifest (builder)
        uses: atlasbytes/github-actions/create-manifest-for-target@0.4.0
        with:
          image-name: ${{ steps.image_name.outputs.lowercase }}
          target: builder
      - name: Create Manifest (builder_nodejs)
        uses: atlasbytes/github-actions/create-manifest-for-target@0.4.0
        with:
          image-name: ${{ steps.image_name.outputs.lowercase }}
          target: builder_nodejs
